"""Built-in provider capability declarations."""

from __future__ import annotations

from zoom_search.models import ProviderCapability


def _openai_compatible_llm_capability(
    engine: str,
    *,
    default_base_url: str,
    supports_reasoning_control: str = "unsupported",
    notes: list[str] | None = None,
    research_sources: list[str] | None = None,
) -> ProviderCapability:
    return ProviderCapability(
        engine=engine,
        provider_kind="builtin",
        protocol="openai_compatible",
        adapter_class="openai_compatible",
        structured_output_level="native_json_object_only",
        tool_calling_level="native_tools_partial",
        streaming_level="sse_full_fidelity",
        execution_model="sync_with_stream",
        supports_structured_output=True,
        supports_json_mode=True,
        supports_streaming=True,
        supports_seed="unsupported",
        supports_parallel_tool_calls="unsupported",
        supports_reasoning_control=supports_reasoning_control,
        supports_usage_reporting="supported",
        supports_finish_reason="supported",
        supports_native_json_schema="unsupported",
        supports_json_object_mode="supported",
        requires_json_keyword_hint=True,
        tool_argument_shape="string_json",
        recommended_query_rewriting_mode="json_object",
        recommended_retry_profile="tolerant_json",
        tool_choice_mode="auto_only",
        tool_result_channel="message_role",
        tool_argument_encoding="json_string",
        default_base_url=default_base_url,
        min_temperature=0.0,
        max_temperature=2.0,
        capability_confidence="medium",
        notes=notes or ["Uses the shared OpenAI-compatible chat completions adapter with conservative JSON-object defaults."],
        research_sources=research_sources or [],
    )


BUILTIN_LLM_CAPABILITIES: dict[str, ProviderCapability] = {
    "openai": ProviderCapability(
        engine="openai",
        provider_kind="builtin",
        protocol="openai_compatible",
        adapter_class="openai_compatible",
        structured_output_level="native_json_schema_strict",
        tool_calling_level="native_tools_full",
        streaming_level="sse_full_fidelity",
        execution_model="sync_with_stream",
        supports_structured_output=True,
        supports_json_mode=True,
        supports_streaming=True,
        supports_seed="supported",
        supports_parallel_tool_calls="supported",
        supports_reasoning_control="patched",
        supports_usage_reporting="supported",
        supports_finish_reason="supported",
        supports_native_json_schema="supported",
        supports_json_object_mode="supported",
        tool_argument_shape="string_json",
        recommended_query_rewriting_mode="json_schema",
        recommended_retry_profile="strict_json",
        tool_choice_mode="auto_required_named",
        tool_result_channel="message_role",
        tool_argument_encoding="json_string",
        research_sources=["OpenAI Chat Completions baseline"],
    ),
    "gemini": ProviderCapability(
        engine="gemini",
        provider_kind="builtin",
        protocol="openai_compatible",
        adapter_class="openai_compatible_patched",
        structured_output_level="native_json_schema_subset",
        tool_calling_level="native_tools_partial",
        streaming_level="sse_full_fidelity",
        execution_model="sync_with_stream",
        supports_structured_output=True,
        supports_json_mode=True,
        supports_streaming=True,
        supports_seed="unsupported",
        supports_parallel_tool_calls="patched",
        supports_reasoning_control="unsupported",
        supports_usage_reporting="supported",
        supports_finish_reason="supported",
        supports_native_json_schema="patched",
        supports_json_object_mode="supported",
        tool_argument_shape="string_json",
        schema_subset_profile="openapi_3_subset",
        client_validation_required=True,
        recommended_query_rewriting_mode="json_schema",
        recommended_retry_profile="strict_json",
        tool_choice_mode="auto_required_named",
        tool_result_channel="message_role",
        tool_argument_encoding="json_string",
        research_sources=["specs/zoom-search/LLM-research/gemini.md"],
    ),
    "doubao-global": ProviderCapability(
        engine="doubao-global",
        provider_kind="builtin",
        protocol="openai_compatible",
        adapter_class="openai_compatible_patched",
        structured_output_level="native_json_schema_subset",
        tool_calling_level="native_tools_full",
        streaming_level="sse_full_fidelity",
        execution_model="sync_with_stream",
        supports_structured_output=True,
        supports_json_mode=True,
        supports_streaming=True,
        supports_seed="unsupported",
        supports_parallel_tool_calls="supported",
        supports_reasoning_control="patched",
        supports_usage_reporting="supported",
        supports_finish_reason="supported",
        supports_native_json_schema="patched",
        supports_json_object_mode="supported",
        tool_argument_shape="string_json",
        schema_subset_profile="provider_custom_subset",
        client_validation_required=True,
        recommended_query_rewriting_mode="json_schema",
        recommended_retry_profile="strict_json",
        tool_choice_mode="auto_required_named",
        tool_result_channel="message_role",
        tool_argument_encoding="json_string",
        notes=["Supports model_id or endpoint_id, injects thinking disabled, and requires an explicit region-specific base_url."],
        research_sources=["specs/zoom-search/LLM-research/doubao-global.md"],
    ),
    "doubao-china": ProviderCapability(
        engine="doubao-china",
        provider_kind="builtin",
        protocol="openai_compatible",
        adapter_class="openai_compatible_patched",
        structured_output_level="native_json_schema_subset",
        tool_calling_level="native_tools_full",
        streaming_level="sse_full_fidelity",
        execution_model="sync_with_stream",
        supports_structured_output=True,
        supports_json_mode=True,
        supports_streaming=True,
        supports_seed="unsupported",
        supports_parallel_tool_calls="supported",
        supports_reasoning_control="patched",
        supports_usage_reporting="supported",
        supports_finish_reason="supported",
        supports_native_json_schema="patched",
        supports_json_object_mode="supported",
        requires_json_keyword_hint=True,
        tool_argument_shape="string_json",
        schema_subset_profile="provider_custom_subset",
        client_validation_required=True,
        recommended_query_rewriting_mode="json_schema",
        recommended_retry_profile="strict_json",
        tool_choice_mode="auto_required_named",
        tool_result_channel="message_role",
        tool_argument_encoding="json_string",
        default_base_url="https://ark.cn-beijing.volces.com/api/v3",
        notes=["Json object mode requires JSON keyword hint and thinking disabled."],
        research_sources=["specs/zoom-search/LLM-research/doubao-china.md"],
    ),
    "qwen-global": ProviderCapability(
        engine="qwen-global",
        provider_kind="builtin",
        protocol="openai_compatible",
        adapter_class="openai_compatible_patched",
        structured_output_level="native_json_object_only",
        tool_calling_level="native_tools_partial",
        streaming_level="sse_full_fidelity",
        execution_model="sync_with_stream",
        supports_structured_output=True,
        supports_json_mode=True,
        supports_streaming=True,
        supports_seed="unsupported",
        supports_parallel_tool_calls="unsupported",
        supports_reasoning_control="patched",
        supports_usage_reporting="supported",
        supports_finish_reason="supported",
        supports_native_json_schema="unsupported",
        supports_json_object_mode="supported",
        requires_json_keyword_hint=True,
        reasoning_pollution_risk="medium",
        tool_argument_shape="string_json",
        recommended_query_rewriting_mode="json_object",
        recommended_retry_profile="strict_json",
        tool_choice_mode="auto_only",
        tool_result_channel="message_role",
        tool_argument_encoding="json_string",
        default_base_url="https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
        min_temperature=0.0,
        max_temperature=1.999,
        notes=["Json schema requests downgrade to json_object with JSON keyword hint."],
        research_sources=["specs/zoom-search/LLM-research/qwen-global.md"],
    ),
    "qwen-china": ProviderCapability(
        engine="qwen-china",
        provider_kind="builtin",
        protocol="openai_compatible",
        adapter_class="openai_compatible_patched",
        structured_output_level="native_json_object_only",
        tool_calling_level="native_tools_partial",
        streaming_level="sse_full_fidelity",
        execution_model="sync_with_stream",
        supports_structured_output=True,
        supports_json_mode=True,
        supports_streaming=True,
        supports_seed="unsupported",
        supports_parallel_tool_calls="patched",
        supports_reasoning_control="patched",
        supports_usage_reporting="supported",
        supports_finish_reason="supported",
        supports_native_json_schema="unsupported",
        supports_json_object_mode="supported",
        requires_json_keyword_hint=True,
        reasoning_pollution_risk="medium",
        tool_argument_shape="string_json",
        recommended_query_rewriting_mode="json_object",
        recommended_retry_profile="strict_json",
        tool_choice_mode="auto_only",
        tool_result_channel="message_role",
        tool_argument_encoding="json_string",
        default_base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        min_temperature=0.0,
        max_temperature=1.999,
        notes=["Json mode uses enable_thinking false and prompt JSON hint."],
        research_sources=["specs/zoom-search/LLM-research/qwen-china.md"],
    ),
    "glm-china": ProviderCapability(
        engine="glm-china",
        provider_kind="builtin",
        protocol="openai_compatible",
        adapter_class="openai_compatible_patched",
        structured_output_level="native_json_object_only",
        tool_calling_level="native_tools_partial",
        streaming_level="sse_full_fidelity",
        execution_model="sync_with_stream",
        supports_structured_output=True,
        supports_json_mode=True,
        supports_streaming=True,
        supports_seed="unsupported",
        supports_parallel_tool_calls="unsupported",
        supports_reasoning_control="patched",
        supports_usage_reporting="supported",
        supports_finish_reason="patched",
        supports_native_json_schema="unsupported",
        supports_json_object_mode="supported",
        tool_argument_shape="mixed",
        recommended_query_rewriting_mode="json_object",
        recommended_retry_profile="strict_json",
        tool_choice_mode="auto_only",
        tool_result_channel="message_role",
        tool_argument_encoding="mixed",
        default_base_url="https://open.bigmodel.cn/api/paas/v4",
        min_temperature=0.0,
        max_temperature=1.0,
        notes=["Determinism is carried by do_sample false and tool_choice is limited to auto."],
        research_sources=["specs/zoom-search/LLM-research/glm-china.md"],
    ),
    "glm-global": ProviderCapability(
        engine="glm-global",
        provider_kind="builtin",
        protocol="openai_compatible",
        adapter_class="openai_compatible_patched",
        structured_output_level="native_json_object_only",
        tool_calling_level="patched_tools",
        streaming_level="sse_full_fidelity",
        execution_model="sync_with_stream",
        supports_structured_output=True,
        supports_json_mode=True,
        supports_streaming=True,
        supports_temperature="patched",
        supports_seed="unsupported",
        supports_stop_sequences="patched",
        supports_parallel_tool_calls="unsupported",
        supports_reasoning_control="patched",
        supports_usage_reporting="supported",
        supports_finish_reason="patched",
        supports_native_json_schema="unsupported",
        supports_json_object_mode="supported",
        requires_json_keyword_hint=True,
        reasoning_pollution_risk="medium",
        tool_argument_shape="mixed",
        recommended_query_rewriting_mode="json_object",
        recommended_retry_profile="tolerant_json",
        tool_choice_mode="auto_only",
        tool_result_channel="message_role",
        tool_argument_encoding="mixed",
        default_base_url="https://api.z.ai/api/paas/v4",
        min_temperature=0.0,
        max_temperature=1.0,
        client_validation_required=True,
        notes=["Uses json_object only, patches mixed tool arguments, and normalizes extended finish reasons."],
        research_sources=["specs/zoom-search/LLM-research/glm-global.md"],
    ),
    "baichuan": ProviderCapability(
        engine="baichuan",
        provider_kind="builtin",
        protocol="openai_compatible",
        adapter_class="openai_compatible_patched",
        structured_output_level="native_json_object_only",
        tool_calling_level="patched_tools",
        streaming_level="sse_full_fidelity",
        execution_model="sync_with_stream",
        supports_structured_output=True,
        supports_json_mode=True,
        supports_streaming=True,
        supports_seed="unsupported",
        supports_parallel_tool_calls="unsupported",
        supports_reasoning_control="unsupported",
        supports_usage_reporting="supported",
        supports_finish_reason="supported",
        supports_native_json_schema="unsupported",
        supports_json_object_mode="supported",
        requires_json_keyword_hint=True,
        tool_argument_shape="string_json",
        recommended_query_rewriting_mode="json_object",
        recommended_retry_profile="tolerant_json",
        tool_choice_mode="auto_required_named",
        tool_result_channel="message_role",
        tool_argument_encoding="json_string",
        default_base_url="https://api.baichuan-ai.com/v1",
        min_temperature=0.0,
        max_temperature=2.0,
        client_validation_required=True,
        notes=["Injects top_k and with_search_enhance defaults, and downgrades schema output to json_object."],
        research_sources=["specs/zoom-search/LLM-research/baichuan.md"],
    ),
    "spark": ProviderCapability(
        engine="spark",
        provider_kind="builtin",
        protocol="openai_compatible",
        adapter_class="openai_compatible_patched",
        structured_output_level="native_json_object_only",
        tool_calling_level="patched_tools",
        streaming_level="sse_full_fidelity",
        execution_model="sync_with_stream",
        supports_structured_output=True,
        supports_json_mode=True,
        supports_streaming=True,
        supports_seed="unsupported",
        supports_parallel_tool_calls="unsupported",
        supports_reasoning_control="unsupported",
        supports_usage_reporting="supported",
        supports_finish_reason="patched",
        supports_native_json_schema="unsupported",
        supports_json_object_mode="supported",
        requires_json_keyword_hint=True,
        tool_argument_shape="string_json",
        recommended_query_rewriting_mode="json_object",
        recommended_retry_profile="tolerant_json",
        tool_choice_mode="auto_required_named",
        tool_result_channel="message_role",
        tool_argument_encoding="json_string",
        error_shape_family="custom",
        default_base_url="https://spark-api-open.xf-yun.com/v1",
        client_validation_required=True,
        notes=["Detects business errors inside HTTP 200 payloads and patches missing finish_reason."],
        research_sources=["specs/zoom-search/LLM-research/spark.md"],
    ),
    "huggingface": ProviderCapability(
        engine="huggingface",
        provider_kind="builtin",
        protocol="openai_compatible",
        adapter_class="openai_compatible_patched",
        structured_output_level="native_json_schema_subset",
        tool_calling_level="unsupported",
        streaming_level="sse_full_fidelity",
        execution_model="sync_with_stream",
        supports_structured_output=True,
        supports_json_mode=True,
        supports_streaming=True,
        supports_seed="supported",
        supports_parallel_tool_calls="unsupported",
        supports_reasoning_control="unsupported",
        supports_usage_reporting="supported",
        supports_finish_reason="supported",
        supports_native_json_schema="patched",
        supports_json_object_mode="patched",
        reasoning_pollution_risk="medium",
        tool_argument_shape="string_json",
        error_shape_family="flat",
        recommended_query_rewriting_mode="json_schema",
        recommended_retry_profile="tolerant_json",
        schema_subset_profile="provider_custom_subset",
        client_validation_required=True,
        tool_choice_mode="none",
        tool_result_channel="unsupported",
        tool_argument_encoding="unsupported",
        default_base_url="https://router.huggingface.co/v1",
        notes=["Rewrites response_format to HuggingFace router format, validates org/model identifiers, and keeps reasoning control model-specific because the router has no documented provider-wide toggle."],
        research_sources=["specs/zoom-search/LLM-research/huggingface.md"],
    ),
    "claude": ProviderCapability(
        engine="claude",
        provider_kind="builtin",
        protocol="native",
        adapter_class="dedicated_native",
        structured_output_level="native_json_schema_strict",
        tool_calling_level="native_tools_full",
        streaming_level="sse_full_fidelity",
        execution_model="sync_with_stream",
        supports_system_message=True,
        supports_multi_message_roles=False,
        supports_structured_output=True,
        supports_json_mode=True,
        supports_streaming=True,
        supports_temperature="patched",
        supports_seed="unsupported",
        supports_stop_sequences="supported",
        supports_parallel_tool_calls="supported",
        supports_reasoning_control="patched",
        supports_usage_reporting="supported",
        supports_finish_reason="patched",
        supports_native_json_schema="supported",
        supports_json_object_mode="patched",
        tool_argument_shape="object_json",
        error_shape_family="nested",
        recommended_query_rewriting_mode="json_schema",
        recommended_retry_profile="strict_json",
        client_validation_required=True,
        tool_choice_mode="provider_custom",
        tool_result_channel="content_block",
        tool_argument_encoding="json_object",
        min_temperature=0.0,
        max_temperature=1.0,
        default_base_url="https://api.anthropic.com",
        research_sources=["specs/zoom-search/LLM-research/claude.md"],
    ),
    "replicate": ProviderCapability(
        engine="replicate",
        provider_kind="builtin",
        protocol="native",
        adapter_class="dedicated_native",
        structured_output_level="prompt_only_json",
        tool_calling_level="unsupported",
        streaming_level="sse_text_only",
        execution_model="hybrid_async_stream",
        supports_system_message=True,
        supports_multi_message_roles=False,
        supports_structured_output=False,
        supports_json_mode=False,
        supports_streaming=True,
        supports_temperature="supported",
        supports_seed="unsupported",
        supports_stop_sequences="patched",
        supports_parallel_tool_calls="unsupported",
        supports_reasoning_control="unsupported",
        supports_usage_reporting="unsupported",
        supports_finish_reason="patched",
        supports_native_json_schema="unsupported",
        supports_json_object_mode="unsupported",
        reasoning_pollution_risk="medium",
        tool_argument_shape="unsupported",
        error_shape_family="stateful_async",
        recommended_query_rewriting_mode="prompt_only_json",
        recommended_retry_profile="async_prediction",
        tool_choice_mode="none",
        tool_result_channel="unsupported",
        tool_argument_encoding="unsupported",
        min_temperature=0.0,
        default_base_url="https://api.replicate.com/v1",
        research_sources=["specs/zoom-search/LLM-research/replicate.md"],
    ),
    "minimax-global": ProviderCapability(
        engine="minimax-global",
        provider_kind="builtin",
        protocol="openai_compatible",
        adapter_class="dual_path",
        structured_output_level="prompt_only_json",
        tool_calling_level="native_tools_partial",
        streaming_level="sse_text_only",
        execution_model="dual_path_sync_or_native",
        supports_json_mode=True,
        supports_streaming=True,
        supports_seed="unsupported",
        supports_parallel_tool_calls="unsupported",
        supports_reasoning_control="patched",
        supports_usage_reporting="supported",
        supports_finish_reason="supported",
        supports_native_json_schema="unsupported",
        supports_json_object_mode="unsupported",
        reasoning_pollution_risk="high",
        tool_argument_shape="string_json",
        recommended_query_rewriting_mode="prompt_only_json",
        recommended_retry_profile="tolerant_json",
        tool_choice_mode="auto_only",
        tool_result_channel="message_role",
        tool_argument_encoding="json_string",
        min_temperature=0.0,
        max_temperature=1.0,
        max_output_tokens_param="max_completion_tokens",
        research_sources=["specs/zoom-search/LLM-research/minimax-global.md"],
    ),
    "minimax-china": ProviderCapability(
        engine="minimax-china",
        provider_kind="builtin",
        protocol="openai_compatible",
        adapter_class="dual_path",
        structured_output_level="native_json_schema_subset",
        tool_calling_level="native_tools_partial",
        streaming_level="sse_text_only",
        execution_model="dual_path_sync_or_native",
        supports_json_mode=True,
        supports_streaming=True,
        supports_seed="unsupported",
        supports_parallel_tool_calls="unsupported",
        supports_reasoning_control="patched",
        supports_usage_reporting="patched",
        supports_finish_reason="supported",
        supports_native_json_schema="patched",
        supports_json_object_mode="unsupported",
        requires_json_keyword_hint=True,
        reasoning_pollution_risk="high",
        tool_argument_shape="string_json",
        error_shape_family="openai_like",
        recommended_query_rewriting_mode="json_schema",
        recommended_retry_profile="tolerant_json",
        schema_subset_profile="provider_custom_subset",
        client_validation_required=True,
        tool_choice_mode="auto_only",
        tool_result_channel="message_role",
        tool_argument_encoding="json_string",
        min_temperature=0.0,
        max_temperature=1.0,
        max_output_tokens_param="max_completion_tokens",
        research_sources=["specs/zoom-search/LLM-research/minimax-china.md"],
    ),
    "deepseek": _openai_compatible_llm_capability(
        "deepseek",
        default_base_url="https://api.deepseek.com/v1",
        supports_reasoning_control="patched",
    ),
    "kimi-china": _openai_compatible_llm_capability(
        "kimi-china",
        default_base_url="https://api.moonshot.cn/v1",
    ),
    "kimi-global": _openai_compatible_llm_capability(
        "kimi-global",
        default_base_url="https://api.moonshot.ai/v1",
    ),
    "yi": _openai_compatible_llm_capability(
        "yi",
        default_base_url="https://api.lingyiwanwu.com/v1",
        notes=["Current public evidence does not confirm a provider-level reasoning disable control in the OpenAI-compatible path."],
    ),
    "hunyuan": _openai_compatible_llm_capability(
        "hunyuan",
        default_base_url="https://tokenhub.tencentmaas.com/v1",
        supports_reasoning_control="patched",
        notes=["Defaults to the TokenHub OpenAI-compatible gateway for current Hunyuan models. Override llm.base_url to use the legacy Hunyuan endpoint when needed."],
    ),
    "stepfun": _openai_compatible_llm_capability(
        "stepfun",
        default_base_url="https://api.stepfun.com/v1",
        notes=["Step reasoning models document reasoning_effort and reasoning_format, but current public docs do not expose a reasoning-off value."],
    ),
    "siliconflow": _openai_compatible_llm_capability(
        "siliconflow",
        default_base_url="https://api.siliconflow.cn/v1",
        supports_reasoning_control="patched",
    ),
    "together": _openai_compatible_llm_capability(
        "together",
        default_base_url="https://api.together.xyz/v1",
        supports_reasoning_control="patched",
        notes=["Supports provider-level reasoning={\"enabled\": false} on chat completions."],
        research_sources=["Together AI chat completions docs"],
    ),
    "fireworks": _openai_compatible_llm_capability(
        "fireworks",
        default_base_url="https://api.fireworks.ai/inference/v1",
        supports_reasoning_control="patched",
    ),
    "groq": _openai_compatible_llm_capability(
        "groq",
        default_base_url="https://api.groq.com/openai/v1",
        supports_reasoning_control="patched",
    ),
    "cerebras": _openai_compatible_llm_capability(
        "cerebras",
        default_base_url="https://api.cerebras.ai/v1",
        supports_reasoning_control="patched",
    ),
    "perplexity": _openai_compatible_llm_capability(
        "perplexity",
        default_base_url="https://api.perplexity.ai",
        notes=["Uses the shared OpenAI-compatible chat completions adapter. Current project evidence does not establish a provider-wide reasoning disable control, so reasoning remains model-specific and only surfaces diagnostics when explicitly turned off."],
        research_sources=["specs/zoom-search/LLM-research/perplexity.md"],
    ),
    "grok": _openai_compatible_llm_capability(
        "grok",
        default_base_url="https://api.x.ai/v1",
        supports_reasoning_control="patched",
    ),
    "mistral": _openai_compatible_llm_capability(
        "mistral",
        default_base_url="https://api.mistral.ai/v1",
        supports_reasoning_control="patched",
    ),
    "cohere": _openai_compatible_llm_capability(
        "cohere",
        default_base_url="https://api.cohere.com/compatibility/v1",
        supports_reasoning_control="patched",
    ),
    "openrouter": _openai_compatible_llm_capability(
        "openrouter",
        default_base_url="https://openrouter.ai/api/v1",
        supports_reasoning_control="patched",
    ),
    "mimo": _openai_compatible_llm_capability(
        "mimo",
        default_base_url="https://api.xiaomimimo.com/v1",
        supports_reasoning_control="patched",
        notes=["Uses the MiMo pay-as-you-go OpenAI-compatible endpoint. Thinking control uses the provider-native thinking object. Token Plan users can override llm.base_url."],
    ),
    "deepinfra": _openai_compatible_llm_capability(
        "deepinfra",
        default_base_url="https://api.deepinfra.com/v1/openai",
        supports_reasoning_control="patched",
    ),
    "novita": _openai_compatible_llm_capability(
        "novita",
        default_base_url="https://api.novita.ai/openai/v1",
        supports_reasoning_control="patched",
    ),
    "hyperbolic": _openai_compatible_llm_capability(
        "hyperbolic",
        default_base_url="https://api.hyperbolic.xyz/v1",
    ),
    "lepton": _openai_compatible_llm_capability(
        "lepton",
        default_base_url="",
        notes=["Uses the shared OpenAI-compatible adapter. Public examples currently point to model-specific Lepton subdomains rather than a single stable provider-wide base URL, so this provider requires an explicit llm.base_url and keeps reasoning control model-specific."],
        research_sources=["specs/zoom-search/LLM-research/lepton.md"],
    ),
    "ollama": _openai_compatible_llm_capability(
        "ollama",
        default_base_url="http://localhost:11434/v1",
        supports_reasoning_control="patched",
        notes=["Uses the local Ollama OpenAI-compatible endpoint. llm.api_key is optional."],
    ),
}

BUILTIN_SEARCH_CAPABILITIES: dict[str, ProviderCapability] = {
    "tavily": ProviderCapability(
        engine="tavily",
        provider_kind="builtin",
        default_base_url="https://api.tavily.com/search",
        supports_site_restriction=True,
        site_restriction_mode="provider_side",
        supports_query_site_operator="unknown",
        recommended_zoom_in_strategy="provider_side",
        query_param_path="query",
        site_param_path="include_domains",
        site_value_type="string_array",
        supports_provider_side_num_results=True,
        num_results_mode="global_limit",
        num_results_param="max_results",
        result_collection_path="results",
        field_candidates={"title": ["title"], "snippet": ["content", "snippet", "description"], "url": ["url"]},
    ),
    "serper": ProviderCapability(
        engine="serper",
        provider_kind="builtin",
        default_base_url="https://google.serper.dev/search",
        supports_site_restriction=False,
        site_restriction_mode="query_side",
        supports_query_site_operator="true",
        recommended_zoom_in_strategy="query_side",
        query_param_path="q",
        supports_provider_side_num_results=True,
        num_results_mode="global_limit",
        num_results_param="num",
        result_collection_path="organic",
        field_candidates={"title": ["title"], "snippet": ["snippet"], "url": ["link", "url"]},
    ),
    "brave": ProviderCapability(
        engine="brave",
        provider_kind="builtin",
        default_base_url="https://api.search.brave.com/res/v1/web/search",
        supports_site_restriction=False,
        site_restriction_mode="query_side",
        supports_query_site_operator="true",
        recommended_zoom_in_strategy="query_side",
        query_param_path="q",
        supports_provider_side_num_results=True,
        num_results_mode="global_limit",
        num_results_param="count",
        result_collection_path="web.results",
        field_candidates={"title": ["title"], "snippet": ["description", "snippet"], "url": ["url"]},
    ),
    "you": ProviderCapability(
        engine="you",
        provider_kind="builtin",
        default_base_url="https://ydc-index.io/v1/search",
        supports_site_restriction=False,
        site_restriction_mode="query_side",
        supports_query_site_operator="true",
        recommended_zoom_in_strategy="query_side",
        query_param_path="query",
        supports_provider_side_num_results=True,
        num_results_mode="per_collection_limit",
        num_results_param="count",
        result_collection_path="results.web",
        field_candidates={"title": ["title"], "snippet": ["description", "snippets", "snippet"], "url": ["url"]},
    ),
    "360search": ProviderCapability(
        engine="360search",
        provider_kind="builtin",
        default_base_url="https://api.360.cn/v2/mwebsearch",
        supports_site_restriction=False,
        site_restriction_mode="query_side",
        supports_query_site_operator="true",
        recommended_zoom_in_strategy="query_side",
        query_param_path="q",
        supports_provider_side_num_results=True,
        num_results_mode="global_limit",
        num_results_param="count",
        result_collection_path="items",
        field_candidates={"title": ["title"], "snippet": ["summary_ai", "summary", "snippet"], "url": ["url"]},
    ),
    "firecrawl": ProviderCapability(
        engine="firecrawl",
        provider_kind="builtin",
        default_base_url="https://api.firecrawl.dev/v2/search",
        supports_site_restriction=True,
        site_restriction_mode="provider_side",
        supports_query_site_operator="true",
        recommended_zoom_in_strategy="provider_side",
        query_param_path="query",
        site_param_path="includeDomains",
        site_value_type="string_array",
        supports_provider_side_num_results=True,
        num_results_mode="per_collection_limit",
        num_results_param="limit",
        result_collection_path="data.web",
        field_candidates={"title": ["title"], "snippet": ["description", "snippet", "content"], "url": ["url"]},
    ),
    "baidu": ProviderCapability(
        engine="baidu",
        provider_kind="builtin",
        default_base_url="https://qianfan.baidubce.com/v2/ai_search/web_search",
        supports_site_restriction=True,
        site_restriction_mode="provider_side",
        supports_query_site_operator="unknown",
        recommended_zoom_in_strategy="provider_side",
        query_param_path="messages[].content",
        site_param_path="search_filter.match.site",
        site_value_type="string_array",
        supports_provider_side_num_results=True,
        num_results_mode="global_limit",
        num_results_param="resource_type_filter[].top_k",
        result_collection_path="references",
        field_candidates={"title": ["title"], "snippet": ["content", "snippet", "description"], "url": ["url", "link"]},
    ),
    "linkup": ProviderCapability(
        engine="linkup",
        provider_kind="builtin",
        default_base_url="https://api.linkup.so/v1/search",
        supports_site_restriction=True,
        site_restriction_mode="provider_side",
        supports_query_site_operator="unknown",
        recommended_zoom_in_strategy="provider_side",
        query_param_path="q",
        site_param_path="includeDomains",
        site_value_type="string_array",
        supports_provider_side_num_results=True,
        num_results_mode="global_limit",
        num_results_param="maxResults",
        result_collection_path="results",
        field_candidates={"title": ["name", "title"], "snippet": ["content", "snippet", "description"], "url": ["url"]},
    ),
    "perplexity": ProviderCapability(
        engine="perplexity",
        provider_kind="builtin",
        default_base_url="https://api.perplexity.ai/search",
        supports_site_restriction=True,
        site_restriction_mode="provider_side",
        supports_query_site_operator="unknown",
        recommended_zoom_in_strategy="provider_side",
        query_param_path="query",
        site_param_path="search_domain_filter",
        site_value_type="string_array",
        supports_provider_side_num_results=True,
        num_results_mode="global_limit",
        num_results_param="max_results",
        result_collection_path="results",
        field_candidates={"title": ["title"], "snippet": ["snippet", "content", "description"], "url": ["url"]},
    ),
    "glm": ProviderCapability(
        engine="glm",
        provider_kind="builtin",
        default_base_url="https://open.bigmodel.cn/api/paas/v4/web_search",
        supports_site_restriction=True,
        site_restriction_mode="provider_side",
        supports_query_site_operator="unknown",
        recommended_zoom_in_strategy="provider_side",
        query_param_path="search_query",
        site_param_path="search_domain_filter",
        site_value_type="string",
        supports_provider_side_num_results=True,
        num_results_mode="global_limit",
        num_results_param="count",
        result_collection_path="search_result",
        field_candidates={"title": ["title"], "snippet": ["content", "snippet", "description"], "url": ["link", "url"]},
    ),
    "volcengine": ProviderCapability(
        engine="volcengine",
        provider_kind="builtin",
        default_base_url="https://open.feedcoopapi.com/search_api/web_search",
        supports_site_restriction=True,
        site_restriction_mode="provider_side",
        supports_query_site_operator="unknown",
        recommended_zoom_in_strategy="provider_side",
        query_param_path="Query",
        site_param_path="Filter.Sites",
        site_value_type="delimiter_string",
        supports_provider_side_num_results=True,
        num_results_mode="global_limit",
        num_results_param="Count",
        result_collection_path="Result.WebResults",
        field_candidates={"title": ["Title", "title", "name"], "snippet": ["Snippet", "Summary", "Content", "snippet", "summary", "content", "description"], "url": ["Url", "url", "source_url", "link"]},
    ),
    "exa": ProviderCapability(
        engine="exa",
        provider_kind="builtin",
        default_base_url="https://api.exa.ai/search",
        supports_site_restriction=True,
        site_restriction_mode="provider_side",
        supports_query_site_operator="unknown",
        recommended_zoom_in_strategy="provider_side",
        query_param_path="query",
        site_param_path="includeDomains",
        site_value_type="string_array",
        supports_provider_side_num_results=True,
        num_results_mode="global_limit",
        num_results_param="numResults",
        result_collection_path="results",
        field_candidates={"title": ["title"], "snippet": ["highlights", "summary", "text", "snippet"], "url": ["url"]},
    ),
    "bocha": ProviderCapability(
        engine="bocha",
        provider_kind="builtin",
        default_base_url="https://api.bochaai.com/v1/web-search",
        supports_site_restriction=True,
        site_restriction_mode="provider_side",
        supports_query_site_operator="unknown",
        recommended_zoom_in_strategy="provider_side",
        query_param_path="query",
        site_param_path="include",
        site_value_type="delimiter_string",
        supports_provider_side_num_results=True,
        num_results_mode="global_limit",
        num_results_param="count",
        result_collection_path="data.webPages.value",
        field_candidates={"title": ["name", "title"], "snippet": ["snippet", "summary", "description"], "url": ["url"]},
    ),
    "querit": ProviderCapability(
        engine="querit",
        provider_kind="builtin",
        default_base_url="https://api.querit.ai/v1/search",
        supports_site_restriction=True,
        site_restriction_mode="provider_side",
        supports_query_site_operator="unknown",
        recommended_zoom_in_strategy="provider_side",
        query_param_path="query",
        site_param_path="filters.sites.include",
        site_value_type="string_array",
        supports_provider_side_num_results=True,
        num_results_mode="global_limit",
        num_results_param="count",
        result_collection_path="results.result",
        field_candidates={"title": ["title"], "snippet": ["snippet", "description", "content"], "url": ["url"]},
    ),
    "serpapi": ProviderCapability(
        engine="serpapi",
        provider_kind="builtin",
        default_base_url="https://serpapi.com/search",
        supports_site_restriction=True,
        site_restriction_mode="provider_side",
        supports_query_site_operator="true",
        recommended_zoom_in_strategy="provider_side",
        query_param_path="q",
        site_param_path="as_sitesearch",
        site_value_type="string",
        supports_provider_side_num_results=False,
        num_results_mode="unsupported",
        result_collection_path="organic_results",
        field_candidates={"title": ["title"], "snippet": ["snippet", "description"], "url": ["link", "url"]},
    ),
    "metasota": ProviderCapability(
        engine="metasota",
        provider_kind="builtin",
        default_base_url="https://metaso.cn/api/v1/search",
        supports_site_restriction=False,
        site_restriction_mode="query_side",
        supports_query_site_operator="unknown",
        recommended_zoom_in_strategy="best_effort",
        query_param_path="q",
        supports_provider_side_num_results=True,
        num_results_mode="global_limit",
        num_results_param="size",
        result_collection_path="webpages",
        field_candidates={"title": ["title"], "snippet": ["snippet", "summary", "description"], "url": ["link", "url"]},
        capability_confidence="low",
    ),
    "searxng": ProviderCapability(
        engine="searxng",
        provider_kind="builtin",
        supports_site_restriction=False,
        site_restriction_mode="query_side",
        supports_query_site_operator="unknown",
        recommended_zoom_in_strategy="best_effort",
        query_param_path="q",
        supports_provider_side_num_results=False,
        num_results_mode="unsupported",
        result_collection_path="results",
        field_candidates={"title": ["title"], "snippet": ["content", "description", "snippet"], "url": ["url"]},
        capability_confidence="low",
    ),
    "tiangong": ProviderCapability(
        engine="tiangong",
        provider_kind="builtin",
        default_base_url="https://api.singularity-ai.com/sky-saas-search/api/v1/search",
        supports_site_restriction=False,
        site_restriction_mode="query_side",
        supports_query_site_operator="unknown",
        recommended_zoom_in_strategy="best_effort",
        query_param_path="content",
        supports_provider_side_num_results=False,
        num_results_mode="unsupported",
        result_collection_path="results",
        field_candidates={"title": ["title"], "snippet": ["snippet"], "url": ["seeMoreUrl"]},
        capability_confidence="low",
    ),
}

DEMO_LLM_CAPABILITY = ProviderCapability(
    engine="demo_llm_provider",
    provider_kind="demo",
    protocol="openai_compatible",
    adapter_class="openai_compatible",
    structured_output_level="native_json_schema_strict",
    tool_calling_level="native_tools_full",
    streaming_level="unsupported",
    supports_structured_output=True,
    supports_json_mode=True,
    supports_seed="supported",
    supports_usage_reporting="supported",
    supports_finish_reason="supported",
    supports_native_json_schema="supported",
    supports_json_object_mode="supported",
    recommended_query_rewriting_mode="json_schema",
    recommended_retry_profile="strict_json",
)

DEMO_SEARCH_CAPABILITY = ProviderCapability(
    engine="demo_search_provider",
    provider_kind="demo",
    supports_site_restriction=True,
    site_restriction_mode="provider_side",
    supports_query_site_operator="true",
    recommended_zoom_in_strategy="provider_side",
    query_param_path="query",
    site_param_path="site",
    site_value_type="string",
    supports_provider_side_num_results=True,
    num_results_mode="global_limit",
    num_results_param="num_results",
    result_collection_path="results",
    field_candidates={"title": ["title"], "snippet": ["snippet"], "url": ["url"]},
)
